- fix in checking is netforking is up.
Changed files:
    lpd.init -> 1.5

diff --git a/lpd.init b/lpd.init
--- a/lpd.init
+++ b/lpd.init
@@ -22,7 +22,10 @@
 [ -f /etc/sysconfig/lpd ] && . /etc/sysconfig/lpd
 
 # Check that networking is up.
-[ "${NETWORKING}" = "no" ] && echo "Error: Networking is down" && exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Lpd can't be runed."
+	exit 1
+fi
 
 # Sanity check
 [ -f /etc/printcap ] || exit 0
